include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    missing_required_param: error
    unused_local_variable: error
    missing_return: warning
  exclude:
    - '**/*.g.dart'
    - 'lib/generated/**'

linter:
  rules:
    avoid_print: true
    prefer_const_constructors: true
    unnecessary_new: true
    prefer_final_locals: true
    always_specify_types: false
    use_key_in_widget_constructors: true
    sized_box_for_whitespace: true

dartdoc:
  warnings:
    undocumented: ignore
    undocumented_public_members: ignore

language:
  strict-casts: true
  strict-inference: true