import 'package:phone_number_view/src/phone_numbers_parser/phone_numbers_parser.dart';

import 'package:phone_number_view/src/phone_numbers_parser/metadata.dart' show metadataByIsoCode;

class PhoneNumberStringConst {
  static String countryDialCode(IsoCode isoCode) {
    return metadataByIsoCode[isoCode]?.countryCode ?? '';
  }

  static String countryName(IsoCode isoCode) {
    return switch (isoCode) {
      IsoCode.AC => ac_,
      IsoCode.AD => ad_,
      IsoCode.AE => ae_,
      IsoCode.AF => af_,
      IsoCode.AG => ag_,
      IsoCode.AI => ai_,
      IsoCode.AL => al_,
      IsoCode.AM => am_,
      IsoCode.AO => ao_,
      IsoCode.AR => ar_,
      IsoCode.AS => as_,
      IsoCode.AT => at_,
      IsoCode.AU => au_,
      IsoCode.AW => aw_,
      IsoCode.AX => ax_,
      IsoCode.AZ => az_,
      IsoCode.BA => ba_,
      IsoCode.BB => bb_,
      IsoCode.BD => bd_,
      IsoCode.BE => be_,
      IsoCode.BF => bf_,
      IsoCode.BG => bg_,
      IsoCode.BH => bh_,
      IsoCode.BI => bi_,
      IsoCode.BJ => bj_,
      IsoCode.BL => bl_,
      IsoCode.BM => bm_,
      IsoCode.BN => bn_,
      IsoCode.BO => bo_,
      IsoCode.BQ => bq_,
      IsoCode.BR => br_,
      IsoCode.BS => bs_,
      IsoCode.BT => bt_,
      IsoCode.BW => bw_,
      IsoCode.BY => by_,
      IsoCode.BZ => bz_,
      IsoCode.CA => ca_,
      IsoCode.CC => cc_,
      IsoCode.CD => cd_,
      IsoCode.CF => cf_,
      IsoCode.CG => cg_,
      IsoCode.CH => ch_,
      IsoCode.CI => ci_,
      IsoCode.CK => ck_,
      IsoCode.CL => cl_,
      IsoCode.CM => cm_,
      IsoCode.CN => cn_,
      IsoCode.CO => co_,
      IsoCode.CR => cr_,
      IsoCode.CU => cu_,
      IsoCode.CV => cv_,
      IsoCode.CW => cw_,
      IsoCode.CX => cx_,
      IsoCode.CY => cy_,
      IsoCode.CZ => cz_,
      IsoCode.DE => de_,
      IsoCode.DJ => dj_,
      IsoCode.DK => dk_,
      IsoCode.DM => dm_,
      IsoCode.DO => do_,
      IsoCode.DZ => dz_,
      IsoCode.EC => ec_,
      IsoCode.EE => ee_,
      IsoCode.EG => eg_,
      IsoCode.EH => eh_,
      IsoCode.ER => er_,
      IsoCode.ES => es_,
      IsoCode.ET => et_,
      IsoCode.FI => fi_,
      IsoCode.FJ => fj_,
      IsoCode.FK => fk_,
      IsoCode.FM => fm_,
      IsoCode.FO => fo_,
      IsoCode.FR => fr_,
      IsoCode.GA => ga_,
      IsoCode.GB => gb_,
      IsoCode.GD => gd_,
      IsoCode.GE => ge_,
      IsoCode.GF => gf_,
      IsoCode.GG => gg_,
      IsoCode.GH => gh_,
      IsoCode.GI => gi_,
      IsoCode.GL => gl_,
      IsoCode.GM => gm_,
      IsoCode.GN => gn_,
      IsoCode.GP => gp_,
      IsoCode.GQ => gq_,
      IsoCode.GR => gr_,
      IsoCode.GT => gt_,
      IsoCode.GU => gu_,
      IsoCode.GW => gw_,
      IsoCode.GY => gy_,
      IsoCode.HK => hk_,
      IsoCode.HN => hn_,
      IsoCode.HR => hr_,
      IsoCode.HT => ht_,
      IsoCode.HU => hu_,
      IsoCode.ID => id_,
      IsoCode.IE => ie_,
      IsoCode.IL => il_,
      IsoCode.IM => im_,
      IsoCode.IN => in_,
      IsoCode.IO => io_,
      IsoCode.IQ => iq_,
      IsoCode.IR => ir_,
      IsoCode.IS => is_,
      IsoCode.IT => it_,
      IsoCode.JE => je_,
      IsoCode.JM => jm_,
      IsoCode.JO => jo_,
      IsoCode.JP => jp_,
      IsoCode.KE => ke_,
      IsoCode.KG => kg_,
      IsoCode.KH => kh_,
      IsoCode.KI => ki_,
      IsoCode.KM => km_,
      IsoCode.KN => kn_,
      IsoCode.KP => kp_,
      IsoCode.KR => kr_,
      IsoCode.KW => kw_,
      IsoCode.KY => ky_,
      IsoCode.KZ => kz_,
      IsoCode.LA => la_,
      IsoCode.LB => lb_,
      IsoCode.LC => lc_,
      IsoCode.LI => li_,
      IsoCode.LK => lk_,
      IsoCode.LR => lr_,
      IsoCode.LS => ls_,
      IsoCode.LT => lt_,
      IsoCode.LU => lu_,
      IsoCode.LV => lv_,
      IsoCode.LY => ly_,
      IsoCode.MA => ma_,
      IsoCode.MC => mc_,
      IsoCode.MD => md_,
      IsoCode.ME => me_,
      IsoCode.MF => mf_,
      IsoCode.MG => mg_,
      IsoCode.MH => mh_,
      IsoCode.MK => mk_,
      IsoCode.ML => ml_,
      IsoCode.MM => mm_,
      IsoCode.MN => mn_,
      IsoCode.MO => mo_,
      IsoCode.MP => mp_,
      IsoCode.MQ => mq_,
      IsoCode.MR => mr_,
      IsoCode.MS => ms_,
      IsoCode.MT => mt_,
      IsoCode.MU => mu_,
      IsoCode.MV => mv_,
      IsoCode.MW => mw_,
      IsoCode.MX => mx_,
      IsoCode.MY => my_,
      IsoCode.MZ => mz_,
      IsoCode.NA => na_,
      IsoCode.NC => nc_,
      IsoCode.NE => ne_,
      IsoCode.NF => nf_,
      IsoCode.NG => ng_,
      IsoCode.NI => ni_,
      IsoCode.NL => nl_,
      IsoCode.NO => no_,
      IsoCode.NP => np_,
      IsoCode.NR => nr_,
      IsoCode.NU => nu_,
      IsoCode.NZ => nz_,
      IsoCode.OM => om_,
      IsoCode.PA => pa_,
      IsoCode.PE => pe_,
      IsoCode.PF => pf_,
      IsoCode.PG => pg_,
      IsoCode.PH => ph_,
      IsoCode.PK => pk_,
      IsoCode.PL => pl_,
      IsoCode.PM => pm_,
      IsoCode.PR => pr_,
      IsoCode.PS => ps_,
      IsoCode.PT => pt_,
      IsoCode.PW => pw_,
      IsoCode.PY => py_,
      IsoCode.QA => qa_,
      IsoCode.RE => re_,
      IsoCode.RO => ro_,
      IsoCode.RS => rs_,
      IsoCode.RU => ru_,
      IsoCode.RW => rw_,
      IsoCode.SA => sa_,
      IsoCode.SB => sb_,
      IsoCode.SC => sc_,
      IsoCode.SD => sd_,
      IsoCode.SE => se_,
      IsoCode.SG => sg_,
      IsoCode.SH => sh_,
      IsoCode.SI => si_,
      IsoCode.SJ => sj_,
      IsoCode.SK => sk_,
      IsoCode.SL => sl_,
      IsoCode.SM => sm_,
      IsoCode.SN => sn_,
      IsoCode.SO => so_,
      IsoCode.SR => sr_,
      IsoCode.SS => ss_,
      IsoCode.ST => st_,
      IsoCode.SV => sv_,
      IsoCode.SX => sx_,
      IsoCode.SY => sy_,
      IsoCode.SZ => sz_,
      IsoCode.TA => ta_,
      IsoCode.TC => tc_,
      IsoCode.TD => td_,
      IsoCode.TG => tg_,
      IsoCode.TH => th_,
      IsoCode.TJ => tj_,
      IsoCode.TK => tk_,
      IsoCode.TL => tl_,
      IsoCode.TM => tm_,
      IsoCode.TN => tn_,
      IsoCode.TO => to_,
      IsoCode.TR => tr_,
      IsoCode.TT => tt_,
      IsoCode.TV => tv_,
      IsoCode.TW => tw_,
      IsoCode.TZ => tz_,
      IsoCode.UA => ua_,
      IsoCode.UG => ug_,
      IsoCode.US => us_,
      IsoCode.UY => uy_,
      IsoCode.UZ => uz_,
      IsoCode.VA => va_,
      IsoCode.VC => vc_,
      IsoCode.VE => ve_,
      IsoCode.VG => vg_,
      IsoCode.VI => vi_,
      IsoCode.VN => vn_,
      IsoCode.VU => vu_,
      IsoCode.WF => wf_,
      IsoCode.WS => ws_,
      IsoCode.XK => xk_,
      IsoCode.YE => ye_,
      IsoCode.YT => yt_,
      IsoCode.ZA => za_,
      IsoCode.ZM => zm_,
      IsoCode.ZW => zw_,
    };
  }

  static const String invalidPhoneNumber = "Invalid phone number";
  static const String invalidCountry = "Invalid country";
  static const String invalidMobilePhoneNumber = "Invalid mobile phone number";
  static const String invalidFixedLinePhoneNumber = "Invalid fixed line phone number";
  static const String requiredPhoneNumber = "Required phone number";
  static const String selectACountrySemanticLabel = "Select a country. Current selection: {countryName} {dialCode}";
  static const String phoneNumber = "Phone number";
  static const String currentValueSemanticLabel = "Current value: {currentValue}";

  // All strings for flutter_country_selector package
  static const String noResultMessage = "No result";
  static const String search = "Search";
  static const String typeToSearch = "Type here to search for a country";
  static const String selectCountry = "Select {country}";
  static const String ac_ = "Ascension Island";
  static const String ad_ = "Andorra";
  static const String ae_ = "United Arab Emirates";
  static const String af_ = "Afghanistan";
  static const String ag_ = "Antigua and Barbuda";
  static const String ai_ = "Anguilla";
  static const String al_ = "Albania";
  static const String am_ = "Armenia";
  static const String an_ = "Netherlands Antilles";
  static const String ao_ = "Angola";
  static const String aq_ = "Antarctica";
  static const String ar_ = "Argentina";
  static const String as_ = "American Samoa";
  static const String at_ = "Austria";
  static const String au_ = "Australia";
  static const String aw_ = "Aruba";
  static const String ax_ = "Aland Islands";
  static const String az_ = "Azerbaijan";
  static const String ba_ = "Bosnia and Herzegovina";
  static const String bb_ = "Barbados";
  static const String bd_ = "Bangladesh";
  static const String be_ = "Belgium";
  static const String bf_ = "Burkina Faso";
  static const String bg_ = "Bulgaria";
  static const String bh_ = "Bahrain";
  static const String bi_ = "Burundi";
  static const String bj_ = "Benin";
  static const String bl_ = "Saint Barthelemy";
  static const String bm_ = "Bermuda";
  static const String bn_ = "Brunei Darussalam";
  static const String bo_ = "Bolivia, Plurinational State of";
  static const String bq_ = "Bonaire";
  static const String br_ = "Brazil";
  static const String bs_ = "Bahamas";
  static const String bt_ = "Bhutan";
  static const String bw_ = "Botswana";
  static const String by_ = "Belarus";
  static const String bz_ = "Belize";
  static const String ca_ = "Canada";
  static const String cc_ = "Cocos (Keeling) Islands";
  static const String cd_ = "Congo, The Democratic Republic of the Congo";
  static const String cf_ = "Central African Republic";
  static const String cg_ = "Congo";
  static const String ch_ = "Switzerland";
  static const String ci_ = "Ivory Coast";
  static const String ck_ = "Cook Islands";
  static const String cl_ = "Chile";
  static const String cm_ = "Cameroon";
  static const String cn_ = "China";
  static const String co_ = "Colombia";
  static const String cr_ = "Costa Rica";
  static const String cu_ = "Cuba";
  static const String cv_ = "Cape Verde";
  static const String cw_ = "Curaçao";
  static const String cx_ = "Christmas Island";
  static const String cy_ = "Cyprus";
  static const String cz_ = "Czech Republic";
  static const String de_ = "Germany";
  static const String dj_ = "Djibouti";
  static const String dk_ = "Denmark";
  static const String dm_ = "Dominica";
  static const String do_ = "Dominican Republic";
  static const String dz_ = "Algeria";
  static const String ec_ = "Ecuador";
  static const String ee_ = "Estonia";
  static const String eg_ = "Egypt";
  static const String eh_ = "Western Sahara";
  static const String er_ = "Eritrea";
  static const String es_ = "Spain";
  static const String et_ = "Ethiopia";
  static const String fi_ = "Finland";
  static const String fj_ = "Fiji";
  static const String fk_ = "Falkland Islands (Malvinas)";
  static const String fm_ = "Micronesia, Federated States of Micronesia";
  static const String fo_ = "Faroe Islands";
  static const String fr_ = "France";
  static const String ga_ = "Gabon";
  static const String gb_ = "United Kingdom";
  static const String gd_ = "Grenada";
  static const String ge_ = "Georgia";
  static const String gf_ = "French Guiana";
  static const String gg_ = "Guernsey";
  static const String gh_ = "Ghana";
  static const String gi_ = "Gibraltar";
  static const String gl_ = "Greenland";
  static const String gm_ = "Gambia";
  static const String gn_ = "Guinea";
  static const String gp_ = "Guadeloupe";
  static const String gq_ = "Equatorial Guinea";
  static const String gr_ = "Greece";
  static const String gs_ = "South Georgia and the South Sandwich Islands";
  static const String gt_ = "Guatemala";
  static const String gu_ = "Guam";
  static const String gw_ = "Guinea-Bissau";
  static const String gy_ = "Guyana";
  static const String hk_ = "Hong Kong";
  static const String hn_ = "Honduras";
  static const String hr_ = "Croatia";
  static const String ht_ = "Haiti";
  static const String hu_ = "Hungary";
  static const String id_ = "Indonesia";
  static const String ie_ = "Ireland";
  static const String il_ = "Israel";
  static const String im_ = "Isle of Man";
  static const String in_ = "India";
  static const String io_ = "British Indian Ocean Territory";
  static const String iq_ = "Iraq";
  static const String ir_ = "Iran, Islamic Republic of";
  static const String is_ = "Iceland";
  static const String it_ = "Italy";
  static const String je_ = "Jersey";
  static const String jm_ = "Jamaica";
  static const String jo_ = "Jordan";
  static const String jp_ = "Japan";
  static const String ke_ = "Kenya";
  static const String kg_ = "Kyrgyzstan";
  static const String kh_ = "Cambodia";
  static const String ki_ = "Kiribati";
  static const String km_ = "Comoros";
  static const String kn_ = "Saint Kitts and Nevis";
  static const String kp_ = "Korea, Democratic People's Republic of Korea";
  static const String kr_ = "Korea, Republic of South Korea";
  static const String kw_ = "Kuwait";
  static const String ky_ = "Cayman Islands";
  static const String kz_ = "Kazakhstan";
  static const String la_ = "Laos";
  static const String lb_ = "Lebanon";
  static const String lc_ = "Saint Lucia";
  static const String li_ = "Liechtenstein";
  static const String lk_ = "Sri Lanka";
  static const String lr_ = "Liberia";
  static const String ls_ = "Lesotho";
  static const String lt_ = "Lithuania";
  static const String lu_ = "Luxembourg";
  static const String lv_ = "Latvia";
  static const String ly_ = "Libya";
  static const String ma_ = "Morocco";
  static const String mc_ = "Monaco";
  static const String md_ = "Moldova";
  static const String me_ = "Montenegro";
  static const String mf_ = "Saint Martin";
  static const String mg_ = "Madagascar";
  static const String mh_ = "Marshall Islands";
  static const String mk_ = "Macedonia";
  static const String ml_ = "Mali";
  static const String mm_ = "Myanmar";
  static const String mn_ = "Mongolia";
  static const String mo_ = "Macao";
  static const String mp_ = "Northern Mariana Islands";
  static const String mq_ = "Martinique";
  static const String mr_ = "Mauritania";
  static const String ms_ = "Montserrat";
  static const String mt_ = "Malta";
  static const String mu_ = "Mauritius";
  static const String mv_ = "Maldives";
  static const String mw_ = "Malawi";
  static const String mx_ = "Mexico";
  static const String my_ = "Malaysia";
  static const String mz_ = "Mozambique";
  static const String na_ = "Namibia";
  static const String nc_ = "New Caledonia";
  static const String ne_ = "Niger";
  static const String nf_ = "Norfolk Island";
  static const String ng_ = "Nigeria";
  static const String ni_ = "Nicaragua";
  static const String nl_ = "Netherlands";
  static const String no_ = "Norway";
  static const String np_ = "Nepal";
  static const String nr_ = "Nauru";
  static const String nu_ = "Niue";
  static const String nz_ = "New Zealand";
  static const String om_ = "Oman";
  static const String pa_ = "Panama";
  static const String pe_ = "Peru";
  static const String pf_ = "French Polynesia";
  static const String pg_ = "Papua New Guinea";
  static const String ph_ = "Philippines";
  static const String pk_ = "Pakistan";
  static const String pl_ = "Poland";
  static const String pm_ = "Saint Pierre and Miquelon";
  static const String pn_ = "Pitcairn";
  static const String pr_ = "Puerto Rico";
  static const String ps_ = "Palestinian Territory, Occupied";
  static const String pt_ = "Portugal";
  static const String pw_ = "Palau";
  static const String py_ = "Paraguay";
  static const String qa_ = "Qatar";
  static const String re_ = "Reunion";
  static const String ro_ = "Romania";
  static const String rs_ = "Serbia";
  static const String ru_ = "Russia";
  static const String rw_ = "Rwanda";
  static const String sa_ = "Saudi Arabia";
  static const String sb_ = "Solomon Islands";
  static const String sc_ = "Seychelles";
  static const String sd_ = "Sudan";
  static const String se_ = "Sweden";
  static const String sg_ = "Singapore";
  static const String sh_ = "Saint Helena";
  static const String si_ = "Slovenia";
  static const String sj_ = "Svalbard and Jan Mayen";
  static const String sk_ = "Slovakia";
  static const String sl_ = "Sierra Leone";
  static const String sm_ = "San Marino";
  static const String sn_ = "Senegal";
  static const String so_ = "Somalia";
  static const String sr_ = "Suriname";
  static const String ss_ = "South Sudan";
  static const String st_ = "Sao Tome and Principe";
  static const String sv_ = "El Salvador";
  static const String sx_ = "Sint Maarten";
  static const String sy_ = "Syrian Arab Republic";
  static const String sz_ = "Swaziland";
  static const String ta_ = "Tristan da Cunha";
  static const String tc_ = "Turks and Caicos Islands";
  static const String td_ = "Chad";
  static const String tg_ = "Togo";
  static const String th_ = "Thailand";
  static const String tj_ = "Tajikistan";
  static const String tk_ = "Tokelau";
  static const String tl_ = "Timor-Leste";
  static const String tm_ = "Turkmenistan";
  static const String tn_ = "Tunisia";
  static const String to_ = "Tonga";
  static const String tr_ = "Türkiye";
  static const String tt_ = "Trinidad and Tobago";
  static const String tv_ = "Tuvalu";
  static const String tw_ = "Taiwan";
  static const String tz_ = "Tanzania, United Republic of Tanzania";
  static const String ua_ = "Ukraine";
  static const String ug_ = "Uganda";
  static const String us_ = "United States";
  static const String uy_ = "Uruguay";
  static const String uz_ = "Uzbekistan";
  static const String va_ = "Holy See (Vatican City State)";
  static const String vc_ = "Saint Vincent and the Grenadines";
  static const String ve_ = "Venezuela";
  static const String vg_ = "Virgin Islands, British";
  static const String vi_ = "Virgin Islands, U.S.";
  static const String vn_ = "Vietnam";
  static const String vu_ = "Vanuatu";
  static const String wf_ = "Wallis and Futuna";
  static const String ws_ = "Samoa";
  static const String xk_ = "Kosovo";
  static const String ye_ = "Yemen";
  static const String yt_ = "Mayotte";
  static const String za_ = "South Africa";
  static const String zm_ = "Zambia";
  static const String zw_ = "Zimbabwe";
}